version: '3'

services:
   postgres:
      image: 'postgres:latest'
      container_name: postgres-udemy
      restart: always
      environment:
         - POSTGRES_USER=userPostgres
         - POSTGRES_DB=go_finance
         - POSTGRES_PASSWORD=senhaPostgres
         - TimeZone=America/Sao_Paulo
      ports:
         - '5432:5432'
      volumes:
         - /home/betocalestini/postgres-udemy:/var/lib/postgresql/data
         - ./db/migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
      networks:
         rede1:
            # aliases:
            #    - database

   pgadmin-compose:
      image: dpage/pgadmin4
      container_name: pgadmin-udemy
      restart: always
      environment:
         PGADMIN_DEFAULT_EMAIL: 'betocalestini@hotmail.com'
         PGADMIN_DEFAULT_PASSWORD: 'senhaPgAdmin'
         TimeZone: 'America/Sao_Paulo'
      ports:
         - '8080:80'
      depends_on:
         - postgres
      networks:
         - rede1

   # sqlc:
   #    image: 'kjconroy/sqlc:latest'
   #    container_name: sqlc-udemy
   #    networks:
   #       - rede1

networks:
   rede1:
      name: rede1
      driver: bridge

   # mysql-workbench:
   #    image: linuxserver/mysql-workbench:latest
   #    container_name: mysql-workbench
   #    environment:
   #       - PUID=1000
   #       - PGID=1000
   #       - TZ=America/Sao_Paulo
   #    volumes:
   #       - /home/betocalestini/mysqlwb/config:/config
   #    ports:
   #       - 3000:3000
   #    cap_add:
   #       - IPC_LOCK
   #    links:
   #       - db
   #    restart: always
   #    networks:
   #       - rede1

   # mysql:
   #    image: mysql:8.0.30
   #    container_name: mysql-udemy
   #    restart: always
   #    volumes:
   #       - /home/betocalestini/mysqldb:/var/lib/mysql
   #    environment:
   #       - MYSQL_USER=betocalestini
   #       - MYSQL_PASSWORD=senha
   #       - MYSQL_ROOT_PASSWORD=admin
   #       - TZ=America/Sao_Paulo
   #    ports:
   #       - 3307:3306
   #    networks:
   #       - rede1

   # phpmyadmin:
   #    image: phpmyadmin/phpmyadmin:latest
   #    container_name: phpmyadmin-udemy
   #    restart: always
   #    links:
   #       - mysql
   #    ports:
   #       - 3308:80
   #    environment:
   #       PMA_ARBITRARY: 1
   #    networks:
   #       - rede1

   # migrate:
   #    image: migrate/migrate
   #    networks:
   #       - rede1
   #    volumes:
   #       - ./db/migration:/migrations
   #    command:
   #       [
   #          '-path',
   #          '/migrations',
   #          '-database',
   #          'postgres://betocalestini:cpi10@postgres:5432/udemy?sslmode=disable',
   #          'up',
   #          '3',
   #       ]
   #    links:
   #       - postgres
   #    # depdens_on:
   #    #    - postgres
