//Listar usuários
GET http://localhost:8000/users HTTP/1.1


###
//Selecionar usuário por email
GET http://localhost:8000/user/betocalestini@hotmail.com HTTP/1.1


###
//Selecionar usuário por id
GET http://localhost:8000/user/id/12 HTTP/1.1

###
//Criar usuário
POST http://localhost:8000/user HTTP/1.1
content-type: application/json

{
  "name":     "roberto",
  "email":    "betocaclestini@hotmail.com",
  "password": "123456"
}
