// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]GetAccountsRow, error)
	GetAccountsGraph(ctx context.Context, arg GetAccountsGraphParams) (int64, error)
	GetAccountsReports(ctx context.Context, arg GetAccountsReportsParams) ([]uint8, error)
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoriesByTitle(ctx context.Context, title string) ([]Category, error)
	GetCategoryById(ctx context.Context, id int32) (Category, error)
	GetDeletedAccount(ctx context.Context, id int32) (Account, error)
	GetDeletedAccounts(ctx context.Context) ([]Account, error)
	GetDeletedCategories(ctx context.Context) ([]Category, error)
	GetDeletedCategory(ctx context.Context, id int32) (Category, error)
	GetDeletedUser(ctx context.Context, id int32) (User, error)
	GetDeletedUsers(ctx context.Context) ([]User, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
